version: '3.7'

services:
  task_api:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
